<?php

/**
 * @file
 * Defines hooks for card module.
 */

use Drupal\card\Element\Card;
use Drupal\file\Entity\File;
use Drupal\node\NodeInterface;
use Drupal\image\Entity\ImageStyle;

function card_theme() {
  $items['card'] = [
    'variables' => [
      'title' => '',
      'summary' => '',
      'link_text' => '',
      'link_url' => '',
    ],
  ];

  // This could be done in a theme.
  $items['card__image'] = array_merge_recursive([
    'variables' => [
      'image_url' => '',
      'image_alt' => ''
    ],
  ], $items['card']);

  return $items;
}

/**
 * Implements hook_element_info_alter().
 *
 * This should be done in a theme.
 */
function card_element_info_alter(array &$info) {
  if (isset($info['node'])) {
    $info['node']['#pre_render'][] = 'card_node_pre_render';
  }
}

/**
 * #pre_render callback: sets correct theme hook for node.
 *
 * This should be done in a theme.
 */
function card_node_pre_render($element) {
  if ($element['#view_mode'] == 'teaser') {
    $element['#theme'] = 'card';
    $element = Card::preRenderNode($element);

    // Adding variation of the card that has an extra variable.
    $entity = $element['#entity'];
    if ($entity instanceof NodeInterface && $entity->hasField('field_image') && !$entity->get('field_image')->isEmpty()) {
      $element['#theme'] = 'card__image';
      $field_content = $entity->get('field_image')->first()->getValue();
      $file_uri = File::load($field_content['target_id'])->getFileUri();
      $element['#image_url'] = ImageStyle::load('medium')->buildUrl($file_uri);
      $element['#image_alt'] = $field_content['alt'];
    }
  }

  return $element;
}
